import { IAttributes } from './i-attributes';
import { IClasses } from './i-classes';
import { ElementListSource } from './element-list-source';
import { EventHandlerInfo } from './event-handler-info';
import { IElement } from './i-element';
import { ElementNode } from './mock-document-nodes';
export declare class MockElement implements IElement {
    private _element;
    constructor(element?: ElementNode);
    isValid(): boolean;
    getParent(): IElement;
    withChildren(callback: (list: IElement[]) => void): IElement;
    private makeElementList;
    expect(tagName: string): IElement;
    getId(): string | null;
    hasId(): boolean;
    exists(): boolean;
    findAll(elementListLocation: ElementListSource): IElement[];
    selectFirst(selector: string): IElement;
    selectorPath(): string;
    tagName(): string;
    text(_text?: string | undefined): string | IElement;
    html(_html?: string | undefined): string | IElement;
    append(_html: string): IElement;
    prepend(_html: string): IElement;
    remove(): undefined;
    attributes(): IAttributes;
    classes(): IClasses;
    on(args: EventHandlerInfo): void;
    value(): string | undefined;
}
